language: node_js
node_js:
  - "0.10"
  - "0.12"
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# No addons, as FF is up to version 31 on travis-ci
script: npm test
